# Generated by Django 5.0 on 2025-03-04 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('fone', models.CharField(max_length=20, unique=True, verbose_name='Telefone')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('condition', models.CharField(choices=[('nove', 'Novo'), ('usado', 'Usado'), ('semi-novo', 'Semi-novo'), ('quebrado', '(Quebrado)')], max_length=20, verbose_name='Condição')),
                ('sold', models.BooleanField(default=False, verbose_name='Vendido')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.categories', verbose_name='Categoria')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.seller', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.BooleanField(default=False, verbose_name='Capa')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Foto')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem',
                'ordering': ['product'],
            },
        ),
    ]
