# Generated by Django 5.0 on 2025-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name': 'Categorias', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['product'], 'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['name'], 'verbose_name': 'Vendedor', 'verbose_name_plural': 'vendedor'},
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('nove', 'Novo'), ('usado', 'Usado'), ('semi-novo', 'Semi-novo'), ('quebrado', 'Quebrado')], max_length=20, verbose_name='Condição'),
        ),
    ]
