# Generated by Django 5.0 on 2025-03-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_photo_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Vendido'),
        ),
    ]
