# Generated by Django 5.0 on 2025-03-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado'), ('Semi-novo', 'Semi-novo'), ('Quebrado', 'Quebrado')], max_length=20, verbose_name='Condição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=800, verbose_name='Descrição'),
        ),
    ]
